all: genUnitTestCommonFunc genUnitTestIntegerFunc genUnitTestMathFunc genUnitTestRelationalFunc genUnitTestOperator

genUnitTestCommonFunc:
	-python genUnitTestCommonFunc.py

genUnitTestIntegerFunc:
	-python genUnitTestIntegerFunc.py

genUnitTestMathFunc:
	-python genUnitTestMathFunc.py

genUnitTestRelationalFunc:
	-python genUnitTestRelationalFunc.py

genUnitTestOperator:
	-python genUnitTestOperator.py

clean:
	rm -rf ../test