all: frontend

frontend:
	-cd arithmetic_operator && make
	-cd common && make
	-cd integer && make
	-cd math && make
	-cd relational && make
	-cd workitem && make

clean:
	-cd arithmetic_operator && make clean
	-cd common && make clean
	-cd integer && make clean
	-cd math && make clean
	-cd relational && make clean
	-cd workitem && make clean
